# -*- coding: utf-8 -*-
"""Customer_Shopping_Behavior_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BSnjXRGVlNJIna7bkDMOL-nWtjEIGVzY
"""

import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

df.head()

df.info()

df.describe(include = 'all')

df.isnull().sum()

df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

df.isnull().sum()

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)' : 'purchase_amount'})

df.columns

# create a column age_group
labels = ['Young Adult', 'Adult', 'Middle-Aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

df[['age', 'age_group']].head(10)

# create column purchase_frequency_days

frequency_mapping = {
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90

}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

df[['discount_applied', 'promo_code_used']].head(10)

(df['discount_applied'] == df['promo_code_used']).all()

df=df.drop('promo_code_used', axis=1)

df.columns
from sqlalchemy import create_engine

username = "postgres"
password = "04032004"
host = "127.0.0.1"   # IMPORTANT CHANGE
port = "5432"
database = "customer_behavior"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

df.to_sql("customer", engine, if_exists="replace", index=False)

print("Data successfully loaded!")